
/* */
var successRes = {
	"result": 1,
	"success": true,
	"err_msg": "请求处理成功",
	"err_code": 8888
}

var dataTpl = {
	"result": 1,
	"success": true,
	"err_msg": "请求处理成功",
	"err_code": 8888
}


export default {

	// 是否开启本模块mock
	inservice:true,

	uploadFile(){
		return dataTpl
	},

    // 获取门店列表
    getStore(){
        dataTpl.result = [
                {
                    "ID": 29,
                    "address": "321",
                    "area": "321",
                    "areaID": 4,
                    "brandID": 1,
                    "businessEndTime": "22:30",
                    "businessStartTime": "00:30",
                    "cbdID": "108001",
                    "city": "发",
                    "companyID": 1,
                    "companyName": "111",
                    "createTime": 1461144263000,
                    "deptID": 39,
                    "des": "",
                    "latitude": 321,
                    "leadingID": 4,
                    "longitude": 321,
                    "manageType": "106001",
                    "openTime": "2016-04-20",
                    "province": "发",
                    "siteNum": 321,
                    "storeCode": "新澳店",
                    "storeName": "新澳店（有数据）",
                    "storeType": "107001",
                    "valid": 1
                }, {
                    "ID": 30,
                    "address": "玄武湖",
                    "area": "华东",
                    "areaID": 4,
                    "brandID": 1,
                    "businessEndTime": "20:00",
                    "businessStartTime": "10:00",
                    "cbdID": "108002",
                    "city": "南京",
                    "companyID": 1,
                    "companyName": "111",
                    "createTime": 1461482381000,
                    "deptID": 39,
                    "leadingID": 1,
                    "manageType": "106001",
                    "openTime": "2016-04-25",
                    "province": "江苏",
                    "siteNum": 10,
                    "storeCode": "1001",
                    "storeName": "前门店",
                    "storeType": "107001",
                    "valid": 1
                }, {
                    "ID": 31,
                    "address": "1111111",
                    "area": "a",
                    "areaID": 3,
                    "brandID": 1,
                    "businessEndTime": "01:30",
                    "businessStartTime": "00:30",
                    "cbdID": "108002",
                    "city": "a",
                    "companyID": 1,
                    "companyName": "111",
                    "createTime": 1461490981000,
                    "deptID": 37,
                    "latitude": 1,
                    "leadingID": 1,
                    "longitude": 1,
                    "manageType": "106002",
                    "openTime": "2016-04-24",
                    "province": "a",
                    "siteNum": 1,
                    "storeCode": "1001",
                    "storeName": "奥体店",
                    "storeType": "107001",
                    "valid": 1
                }
            ]
        return dataTpl
    },
    // 获取部门列表
    getDepartment(){
        dataTpl.result = [
                {
                    "ID": 30,
                    "companyID": 1,
                    "createTime": 1461143186000,
                    "departmentName": "总公司",
                    "des": "总公司",
                    "leadingID": 4,
                    "leadingName": "张小三",
                    "parentID": -1
                }, {
                    "ID": 33,
                    "companyID": 1,
                    "createTime": 1461143313000,
                    "departmentName": "东北分公司",
                    "des": "东北分公司",
                    "parentID": 30
                }, {
                    "ID": 34,
                    "companyID": 1,
                    "createTime": 1461143337000,
                    "departmentName": "天津分公司",
                    "des": "天津分公司",
                    "leadingID": 6,
                    "leadingName": "李小四",
                    "parentID": 33
                }, {
                    "ID": 35,
                    "companyID": 1,
                    "createTime": 1461143361000,
                    "departmentName": "北京分公司",
                    "des": "北京分公司",
                    "parentID": 30
                }, {
                    "ID": 36,
                    "companyID": 1,
                    "createTime": 1461143371000,
                    "departmentName": "人事部",
                    "des": "人事部",
                    "parentID": 34
                }, {
                    "ID": 37,
                    "companyID": 1,
                    "createTime": 1461143382000,
                    "departmentName": "行政部",
                    "des": "行政部",
                    "parentID": 35
                }, {
                    "ID": 39,
                    "companyID": 1,
                    "createTime": 1461144151000,
                    "departmentName": "运营部（有数据）",
                    "des": "运营部",
                    "parentID": 35
                }, {
                    "ID": 40,
                    "companyID": 1,
                    "createTime": 1461144164000,
                    "departmentName": "总经办",
                    "des": "总经办",
                    "parentID": 33
                }, {
                    "ID": 44,
                    "companyID": 1,
                    "createTime": 1461576642000,
                    "departmentName": "市场部",
                    "des": "人事",
                    "leadingID": 6,
                    "leadingName": "李小四",
                    "parentID": 34
                }, {
                    "ID": 46,
                    "companyID": 1,
                    "createTime": 1462265036000,
                    "departmentName": "测试",
                    "des": "测试",
                    "leadingID": 6,
                    "leadingName": "李小四",
                    "parentID": 33
                }, {
                    "ID": 79,
                    "companyID": 1,
                    "createTime": 1462778308000,
                    "departmentName": "总公司2",
                    "des": "123",
                    "leadingID": 1,
                    "leadingName": "王小二",
                    "parentID": -1
                }
            ]
        return dataTpl
    },
	getOrgList:function(arg){

		dataTpl.result = {
			"companyID": 1,
			"companyName": "111",
			"dept": [
				{
					"ID": 30,
					"companyID": 1,
					"createTime": 1461143186000,
					"departmentName": "总公司",
					"des": "总公司",
					"leadingID": 4,
					"leadingName": "张小三",
					"parentID": -1
				}, {
					"ID": 33,
					"companyID": 1,
					"createTime": 1461143313000,
					"departmentName": "东北分公司",
					"des": "东北分公司",
					"parentID": 30
				}, {
					"ID": 34,
					"companyID": 1,
					"createTime": 1461143337000,
					"departmentName": "天津分公司",
					"des": "天津分公司",
					"leadingID": 6,
					"leadingName": "李小四",
					"parentID": 33
				}, {
					"ID": 35,
					"companyID": 1,
					"createTime": 1461143361000,
					"departmentName": "北京分公司",
					"des": "北京分公司",
					"parentID": 30
				}, {
					"ID": 36,
					"companyID": 1,
					"createTime": 1461143371000,
					"departmentName": "人事部",
					"des": "人事部",
					"parentID": 34
				}, {
					"ID": 37,
					"companyID": 1,
					"createTime": 1461143382000,
					"departmentName": "行政部",
					"des": "行政部",
					"parentID": 35
				}, {
					"ID": 39,
					"companyID": 1,
					"createTime": 1461144151000,
					"departmentName": "运营部（有数据）",
					"des": "运营部",
					"parentID": 35
				}, {
					"ID": 40,
					"companyID": 1,
					"createTime": 1461144164000,
					"departmentName": "总经办",
					"des": "总经办",
					"parentID": 33
				}, {
					"ID": 44,
					"companyID": 1,
					"createTime": 1461576642000,
					"departmentName": "市场部",
					"des": "人事",
					"leadingID": 6,
					"leadingName": "李小四",
					"parentID": 34
				}, {
					"ID": 46,
					"companyID": 1,
					"createTime": 1462265036000,
					"departmentName": "测试",
					"des": "测试",
					"leadingID": 6,
					"leadingName": "李小四",
					"parentID": 33
				}, {
					"ID": 79,
					"companyID": 1,
					"createTime": 1462778308000,
					"departmentName": "总公司2",
					"des": "123",
					"leadingID": 1,
					"leadingName": "王小二",
					"parentID": -1
				}
			],
			"operator": [
				{
					"ID": 1,
					"loginName": "suxin"
				}, {
					"ID": 2,
					"loginName": "zhangsan"
				}, {
					"ID": 12,
					"loginName": "xiachao"
				}, {
					"ID": 13,
					"loginName": "测试者"
				}, {
					"ID": 14,
					"loginName": "2321321"
				}, {
					"ID": 15,
					"loginName": "test1"
				}, {
					"ID": 16,
					"loginName": "fkcd"
				}, {
					"ID": 17,
					"loginName": "12345679"
				}, {
					"ID": 18,
					"loginName": "321"
				}],
				"role": [{
					"ID": 2,
					"roleName": "测试"
				}, {
					"ID": 3,
					"roleName": "zy"
				}, {
					"ID": 4,
					"roleName": "门店管理组"
				}, {
					"ID": 5,
					"roleName": "321312"
				}, {
					"ID": 6,
					"roleName": "邵睿"
				}
			],
			"store": [
				{
					"ID": 29,
					"address": "321",
					"area": "321",
					"areaID": 4,
					"brandID": 1,
					"businessEndTime": "22:30",
					"businessStartTime": "00:30",
					"cbdID": "108001",
					"city": "发",
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461144263000,
					"deptID": 39,
					"des": "",
					"latitude": 321,
					"leadingID": 4,
					"longitude": 321,
					"manageType": "106001",
					"openTime": "2016-04-20",
					"province": "发",
					"siteNum": 321,
					"storeCode": "新澳店",
					"storeName": "新澳店（有数据）",
					"storeType": "107001",
					"valid": 1
				}, {
					"ID": 30,
					"address": "玄武湖",
					"area": "华东",
					"areaID": 4,
					"brandID": 1,
					"businessEndTime": "20:00",
					"businessStartTime": "10:00",
					"cbdID": "108002",
					"city": "南京",
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461482381000,
					"deptID": 39,
					"leadingID": 1,
					"manageType": "106001",
					"openTime": "2016-04-25",
					"province": "江苏",
					"siteNum": 10,
					"storeCode": "1001",
					"storeName": "前门店",
					"storeType": "107001",
					"valid": 1
				}, {
					"ID": 31,
					"address": "1111111",
					"area": "a",
					"areaID": 3,
					"brandID": 1,
					"businessEndTime": "01:30",
					"businessStartTime": "00:30",
					"cbdID": "108002",
					"city": "a",
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461490981000,
					"deptID": 37,
					"latitude": 1,
					"leadingID": 1,
					"longitude": 1,
					"manageType": "106002",
					"openTime": "2016-04-24",
					"province": "a",
					"siteNum": 1,
					"storeCode": "1001",
					"storeName": "奥体店",
					"storeType": "107001",
					"valid": 1
				}
			],
			"storeTeam": [
				{
					"ID": 84,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461144263000,
					"deptID": 39,
					"deptName": "运营部（有数据）",
					"des": "",
					"operatorID": 1,
					"storeID": 29,
					"storeName": "新澳店（有数据）",
					"teamCode": "",
					"teamName": "行政组",
					"valid": 1
				}, {
					"ID": 89,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461482381000,
					"deptID": 39,
					"deptName": "运营部（有数据）",
					"operatorID": 1,
					"storeID": 30,
					"storeName": "前门店",
					"teamName": "厨房组",
					"valid": 1
				}, {
					"ID": 93,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461490981000,
					"deptID": 37,
					"deptName": "行政部",
					"operatorID": 1,
					"storeID": 31,
					"storeName": "奥体店",
					"teamName": "值班组",
					"valid": 1
				}, {
					"ID": 94,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1461490981000,
					"deptID": 37,
					"deptName": "行政部",
					"operatorID": 1,
					"storeID": 31,
					"storeName": "奥体店",
					"teamName": "服务员组",
					"valid": 1
				}, {
					"ID": 95,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1462271503000,
					"deptID": 39,
					"deptName": "运营部（有数据）",
					"storeID": 29,
					"storeName": "新澳店（有数据）",
					"teamName": "配菜组",
					"valid": 1
				}, {
					"ID": 96,
					"companyID": 1,
					"companyName": "111",
					"createTime": 1462271674000,
					"deptID": 39,
					"deptName": "运营部（有数据）",
					"storeID": 29,
					"storeName": "新澳店（有数据）",
					"teamName": "服务组",
					"valid": 1
				}
			]
		}
		return dataTpl

	}
}
